export const DirectoryActionTypes = {
    FETCH_EMPLOYEE_DIRECTORY_START: 'FETCH_EMPLOYEE_DIRECTORY_START',
    FETCH_EMPLOYEE_DIRECTORY_SUCCESS: 'FETCH_EMPLOYEE_DIRECTORY_SUCCESS',
    FETCH_EMPLOYEE_DIRECTORY_FAILURE: 'FETCH_EMPLOYEE_DIRECTORY_FAILURE',
    SET_ACTIVE_EMPLOYEE: 'SET_ACTIVE_EMPLOYEE',
}

